export const COLOR_GENERATOR = {
  GET_RANDOM_COLOR_REQUEST: 'PHOTOS/GET_RANDOM_COLOR_REQUEST',
  GET_RANDOM_COLOR_SUCCESS: 'PHOTOS/GET_RANDOM_COLOR_SUCCESS',
  GET_RANDOM_COLOR_ERROR: 'PHOTOS/GET_RANDOM_COLOR_ERROR',
};
